# kernel/.cargo/config.toml for x86_64
[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = ["-C", "link-args=-Tkernel/link.ld"]