# uefi_bootloader/Cargo.toml
[package]
name = "uefi_bootloader"  # This must match what's in your workspace dependencies
version = "0.0.1"
edition = "2021"

[dependencies]
uefi = "0.19.0"
uefi-services = "0.16.0"
log = "0.4.17"